# Generated by Django 3.1.7 on 2021-03-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='exppires_in',
            new_name='expires_in',
        ),
    ]
